### ISSUE TITLE
Using same orbitcontrols for two canvas

### ISSUE THREAD

**Issue by YarooqH** [TiagoCavalcante/r3f-native-orbitcontrols#12]
Hey! im trying to implement a single orbitcontrol on two canvas placed side by side something like this [jsfiddle] (https://jsfiddle.net/62x8c139/) here and im guessing the second example that you have given in the docs does the same thing that im trying to achieve but when im trying to do it then only one canvas camera moves but both canvas register finger movements. 

Here is my code:
 
`   

    const ThreeD = () => {

    const camera = <PerspectiveCamera />
    
    const[OrbitControls1, events1] = useControls();
    // const[OrbitControls2, events2] = useControls();

    return (
      <View style={{flex: 2}} {...events1}>

      <Canvas gl={{ physicallyCorrectLights: true }} camera={camera} 
      onCreated={(state) => {
        const _gl = state.gl.getContext()
        const pixelStorei = _gl.pixelStorei.bind(_gl)
      _gl.pixelStorei = function(...args) {
        const [parameter] = args
        switch(parameter) {
          case _gl.UNPACK_FLIP_Y_WEBGL:
            return pixelStorei(...args)
        }
      }
    }}
      >
        <Suspense fallback={null}>
        <color attach="background" args={[0x000000]} />
        <directionalLight intensity={1} position={[-6, 2, 2]} />
        <Suspense fallback={<TextComponent />}>
          <Environment preset="park" />
          <TextComponent />
        </Suspense>
        <OrbitControls1 minPolarAngle={Math.PI/2} maxPolarAngle={Math.PI/2} enablePan={false} enableZoom={false} />
        </Suspense>
        </Canvas>

      <Canvas gl={{ physicallyCorrectLights: true }} camera={camera} 
      onCreated={(state) => {
      const _gl = state.gl.getContext()
      const pixelStorei = _gl.pixelStorei.bind(_gl)
      _gl.pixelStorei = function(...args) {
        const [parameter] = args
        switch(parameter) {
          case _gl.UNPACK_FLIP_Y_WEBGL:
            return pixelStorei(...args)
        }
      }
    }}
      >
        <Suspense fallback={null}>
        <color attach="background" args={[0x000000]} />
        <directionalLight intensity={1} position={[-6, 2, 2]} />
        <Suspense fallback={<TextComponent />}>
          <Environment preset="park" />
          <TextComponent />
        </Suspense>
        <OrbitControls1 minPolarAngle={Math.PI/2} maxPolarAngle={Math.PI/2} enablePan={false} enableZoom={false} />
        </Suspense>
        </Canvas>

      </View> 
    )}

`

**Comment by TiagoCavalcante** [comment]
@YarooqH the canvases don't register finger movements, the parent view does. That's what the `{...events}` does.

To have only one of the canvases "registering" finger movements you need to have `{...events}` only in the parent one of the canvases, so your code will look like this:
```jsx
{/* No events here */}
<View style={{ flex: 1 }}>
  {/* Events here */}
  <View style={{ flex: 1 }} {...events}>
    <Canvas camera={camera}>
      ...
    </Canvas>
  </View>

  {/* No events here */}
  <View style={{ flex: 1 }}>
    <Canvas camera={camera}>
      ...
    </Canvas>
  </View>
</View>
```

**Comment by YarooqH** [comment]
Thanks for the quick response @TiagoCavalcante. I am indeed trying to move cameras of both canvas when even one canvas is interacted upon, and i believe the second example in the documentation does the same thing but when i am trying to implement it something like this is happening -> [watch video here](https://www.veed.io/view/b5e73c0a-a884-49b7-abac-83aa291e14ca?sharingWidget=true&panel=share). It could be because im doing something incorrectly.
```js
const ThreeD = () => {
    const config = {
      fov: 75,
      position: [0, 0, 16], 
    }    

    const camera = <PerspectiveCamera {...config}/>
    
    const[OrbitControls1, events1] = useControls();
  
    return (
      <View style={{flex: 1}}>
      <View style={{flex: 1}} {...events1}>
      <Canvas  camera={camera} >
        <Suspense fallback={null}>
        <color attach="background" args={[0x000000]} />
        <directionalLight intensity={1} position={[-6, 2, 2]} />
        <Suspense fallback={<TextComponent />}>
          <Environment preset="park" />
          <TextComponent />
        </Suspense>
        <OrbitControls1 minPolarAngle={Math.PI/2} maxPolarAngle={Math.PI/2} enablePan={false} enableZoom={false} />
        </Suspense>
        </Canvas>
      </View>
      <View style={{flex:1}}>
      <Canvas camera={camera} >
        <Suspense fallback={null}>
        <color attach="background" args={[0x000000]} />
        <directionalLight intensity={1} position={[-6, 2, 2]} />
        <Suspense fallback={<TextComponent />}>
          <Environment preset="park" />
          <TextComponent />
        </Suspense>
        <OrbitControls1 minPolarAngle={Math.PI/2} maxPolarAngle={Math.PI/2} enablePan={false} enableZoom={false} />
        </Suspense>
        </Canvas>
        </View>
      </View>
    )
}

```

**Comment by TiagoCavalcante** [comment]
@YarooqH not sure if I understand, do you want that both canvases be interactive?

**Comment by YarooqH** [comment]
Yeah, it would be great if i can get both canvases to be interactive but it will suffice if only one canvas registers the movements and the movements get reflected on both canvases.

**Comment by YarooqH** [comment]
Yeah @TiagoCavalcante i get it, the example in the documentation should've worked for me but its producing the result as shown in the above linked video and i cant figure out if its because of me doing something stupidly wrong or if it is something else thats causing the trouble.
```js
const ThreeD = () => {
    const config = {
      fov: 75,
      position: [0, 0, 16], 
    }    

    const camera = <PerspectiveCamera {...config}/>
    
    const[OrbitControls, events] = useControls();
  
    return (
      <View style={{flex: 1}}>

      <View style={{flex: 1}} {...events1}>
      <Canvas  camera={camera} >
        <Suspense>
        <Suspense>
          <TextComponent />
        </Suspense>
        <OrbitControls minPolarAngle={Math.PI/2} maxPolarAngle={Math.PI/2} enablePan={false} enableZoom={false} />
        </Suspense>
        </Canvas>
      </View>

      <View style={{flex:1}}>
      <Canvas camera={camera} >
        <Suspense>
        <Suspense>
          <TextComponent />
        </Suspense>
        <OrbitControls minPolarAngle={Math.PI/2} maxPolarAngle={Math.PI/2} enablePan={false} enableZoom={false} />
        </Suspense>
        </Canvas>
        </View>

      </View>
    )
}

```

**Comment by TiagoCavalcante** [comment]
@YarooqH the way you are defining the camera is wrong, it should be as it is in the documentation:
```js
const camera = new PerspectiveCamera()
// Optional:
camera.position.set(10, 10, 10)
camera.lookAt(0, 0, 0)
```

**Comment by YarooqH** [comment]
From where are you importing the Perspective Camera @TiagoCavalcante? because in the my code I'm importing it from "@react-three/drei/native" and when i called it like a constructor it gave me an error that "Perspective Camera is not a callable constructor" thats why i made a component and passed it to the both canvases.

**Comment by TiagoCavalcante** [comment]
@YarooqH you should import that from `three`

I'll update the documentation with this information

**Comment by YarooqH** [comment]
Here are my package versions, 
```json
"react-native": "0.70.6",
"react": "18.1.0",
"expo-gl": "~12.0.1",
"expo": "^47.0.0",
"@react-three/drei": "^9.51.22",
"@react-three/fiber": "^8.10.0",
"three": "^0.148.0"
```

**Comment by TiagoCavalcante** [comment]
@YarooqH try to add the optional part I mentioned above

**Comment by YarooqH** [comment]
It Worked! Thanks! @TiagoCavalcante.

**Comment by TiagoCavalcante** [comment]
@YarooqH great! Thanks for using the library and creating the issue!

**Comment by TiagoCavalcante** [comment]
@YarooqH I have changed the documentation, I hope it is better now!

**Comment by YarooqH** [comment]
That's Great! @TiagoCavalcante. It'll help others when they'll come across to your package when it gets popular, which I'm sure it will soon.

I tried many other orbitcontrols packages even the one from expo but they all had some issues and problems along with them then i came across your package and it worked like a charm and was really easy to setup too. I highly appreciate the efforts that you're making towards the community.
