### ISSUE TITLE
Canvas touch events are not working 

### ISSUE THREAD

**Issue by asadddww** [TiagoCavalcante/r3f-native-orbitcontrols#14]
After adding orbit controls, canvas touch events like onClick on <mesh onClick={()=>alert()} /> has stopped working
I think pan responder is overriding the same. 

any idea on how to fix this ??

**Comment by TiagoCavalcante** [comment]
@asadddww can you send a broader part of your code?

It worked in my tests: [r3f-orbitcontrols-example](https://github.com/TiagoCavalcante/r3f-orbitcontrols-example)

**Comment by asadddww** [comment]
never mind i just worked around it via enabled prop toggling to false and true with Pan responders in parent component

**Comment by TiagoCavalcante** [comment]
Great!

If you still want help with it you can re-open the issue

**Comment by janogarciardz** [comment]
> never mind i just worked around it via enabled prop toggling to false and true with Pan responders in parent component

Hi, could you share your code with me? I have the same problem and I can't find a solution.
