### ISSUE TITLE
Blank canvas upon attempting to use OrbitControls like sample

### ISSUE THREAD

**Issue by luxebo** [TiagoCavalcante/r3f-native-orbitcontrols#2]
I am having trouble getting the package working on emulator with the following code:

    render() {
      const [OrbitControls, events] = useControls();
      return(
        <View style={{flex: 1}} {...events}>
          <Canvas>
            <OrbitControls>
              <mesh>
                <boxGeometry></boxGeometry>
                <meshStandardMaterial></meshStandardMaterial>
              </mesh>
            </OrbitControls>
          </Canvas>
        </View>
        )
}

In my head this should be the basic use flow, which shouldn't need camera definitions or similar right? That should create a cube that allows me to rotate around, similar to react-three-fiber/drei's orbit controls for web?

**Comment by TiagoCavalcante** [comment]
@luxebo the `<OrbirControls />` should be a sibling of the scene elements, not the parent:
```js
render() {
  const [OrbitControls, events] = useControls();
  return(
    <View style={{flex: 1}} {...events}>
      <Canvas>
        <OrbitControls />

        <mesh>
          <boxGeometry></boxGeometry>
          <meshStandardMaterial></meshStandardMaterial>
        </mesh>
      </Canvas>
    </View>
  )
}
```

**Comment by luxebo** [comment]
Thank you- that works! Thanks for having a great package and thanks for responding quickly too!

**Comment by luxebo** [comment]
One more question, how do I pass the canvas' camera into Orbit Controls? It seems they have different cameras, and while I tried using state to store the camera, it seems to break Orbit Controls' functionality.

**Comment by luxebo** [comment]
I don't know why entirely, but below are two images that show a small issue: if I edit the camera for the canvas, with the orbit controls the first image appears, the second image appears without orbit controls. I'm not exactly sure how I can keep the second camera with or without the orbit controls.

<img width="268" alt="with orbit controls" src="https://user-images.githubusercontent.com/34826088/199829141-0eaa20a9-3f15-4935-83e2-b43c0216b20e.PNG">
<img width="269" alt="without orbit controls" src="https://user-images.githubusercontent.com/34826088/199829149-e4c66b01-2e92-4458-85ab-b97b058dd32a.PNG">

**Comment by TiagoCavalcante** [comment]
@luxebo can you show both codes?

**Comment by luxebo** [comment]
This.layers is the generalized cylinder, shouldn't affect anything here, just the camera needs to be changed, making orbit controls implementation smaller.

Without orbit controls:

    render() {
      return(
        <View style={this.styles.canvasView} {...events}>
          <Canvas camera={{position: [0, 15, 15], rotation: [-0.5, 0, 0], zoom: 2.0}}>
            {this.layers}
          </Canvas>
        </View>
      )
    }

With orbit controls:

    render() {
      const [OrbitControls, events] = useControls();
      return(
        <View style={this.styles.canvasView} {...events}>
          <Canvas camera={{position: [0, 15, 15], rotation: [-0.5, 0, 0], zoom: 2.0}}>
            <OrbitControls enableZoom={false} enablePan={false} minPolarAngle={1} maxPolarAngle={1}/>
            {this.layers}
          </Canvas>
        </View>
      )
    }

**Comment by TiagoCavalcante** [comment]
@luxebo this bug happens because in the orbit control the camera is always pointing the target, which is set to be the center of the scene, you could change the target to a bit bellow so the view is close to the one without orbit controls.

**Comment by luxebo** [comment]
Sounds good- I think then the solutions are either to force the object to be centered in the scene, or to simply readjust the camera again. Thanks for the help again!
