### ISSUE TITLE
Feature Request: 'maxDistance', 'minDistance' Props Support and 'setLookAt'/'dollyTo' Methods

### ISSUE THREAD

**Issue by yaroslavnikiforov** [TiagoCavalcante/r3f-native-orbitcontrols#20]
I would like to express my appreciation for the excellent library and its functionalities.  

However, I have identified a need for additional features that would enhance its capabilities even further. Specifically, support for the 'maxDistance' and 'minDistance' props, as well as the inclusion of methods like 'setLookAt' and 'dollyTo', similar to what is available in the 'camera-controls' package. These additional features would greatly enhance the flexibility and functionality of the library.

**Comment by TiagoCavalcante** [comment]
Hi @yaroslavnikiforov 

There is already `minZoom` and `maxZoom` which are equivalent to `minDistance` and `maxDistance`.

`setLookAt` and `dollyTo` would be really a copy-and-paste from the equivalent functions in the `Camera` object, so I believe it doesn't make sense to add them.

Your thoughts?

**Comment by TiagoCavalcante** [comment]
I'm closing this issue now. Please re-open it in case my last comment didn't solve your problem.
