### ISSUE TITLE
Pan vertically with only one finger

### ISSUE THREAD

**Issue by computabeast** [TiagoCavalcante/r3f-native-orbitcontrols#22]
Great project. 

I'm trying to implement a simulated 2D, infinite vertical scroll, and would like OrbitControls to pan the camera vertically with only one finger, rather than being forced to use two (I know this is standard). Is OrbitControls configuration something that we could add to the project, or something that is possible to do in its current state? I'm happy to help out with it myself as well.

**Comment by TiagoCavalcante** [comment]
Hi @computabeast, thanks for creating the issue!

Sorry for the long delay.

I think that you might be looking for [MapControls](https://threejs.org/docs/?q=controls#examples/en/controls/MapControls) instead.

Currently it is not possible to do with this library, but this feature can be added.

Would you like to implement it?

**Comment by TiagoCavalcante** [comment]
I'm closing this, if you still have the issue please re-open it
