### ISSUE TITLE
How to configure maxDistance and minDistance?

### ISSUE THREAD

**Issue by dhikicheeks** [TiagoCavalcante/r3f-native-orbitcontrols#23]
how to configure maxDistance and minDistance? I need that configuration to match the configuration between nextjs Three and react native.
like:
 ```
 <OrbitControls
      maxDistance={1}
      minDistance={0.5}
  />
```
but it throws error **Property 'maxDistance' does not exist**

**Comment by TiagoCavalcante** [comment]
Hi @dhikicheeks, thanks for creating the issue!
Those properties are actually named `maxZoom` and `minZoom`.
