### ISSUE TITLE
Error: The camera must be a PerspectiveCamera to orbit controls work

### ISSUE THREAD

**Issue by Osmanity** [TiagoCavalcante/r3f-native-orbitcontrols#24]
Im using r3f-native library which works as charm, but the thing is that I want to change the camera to orthographic instead of Perspective but gets me the following error: 

Error: The camera must be a PerspectiveCamera to orbit controls work

Here is my code: 

<Canvas orthographic camera={{ zoom: 50, position: [0, 0, 100] }}>
          <OrbitControls />
          <pointLight position={[10, 10, 10]} />
          {* <Suspense fallback={null}>
            <Box /> 
          </Suspense>*}
</Canvas>

Thanks!:)

**Comment by TiagoCavalcante** [comment]
Hi @Osmanity, thanks for creating the issue!
I have released a new version that adds support to OrtographicCamera's.

**Comment by Osmanity** [comment]
Thanks for the quick reply, will try it later this evening!:)
