### ISSUE TITLE
Firefox   vs   chrome/expo app

### ISSUE THREAD

**Issue by MainzerKaiser** [TiagoCavalcante/r3f-native-orbitcontrols#30]
Hello,

I am relatively new to the native development environment and have encountered an issue in my project, which I was able to reproduce using the example code provided in the r3f-orbitcontrols-example repository (https://github.com/TiagoCavalcante/r3f-orbitcontrols-example).

When testing the web version in Firefox, the orbit controls respond smoothly to every click or touch event.

However, when testing the web version in Chrome or opening the Android version in the Expo Go app, I noticed that only every second click event triggers a reaction. I have confirmed this by tracking the click events using the onChange event and logging the results to the console. It seems that not every click is being consistently tracked.

I would like to understand if anyone else has encountered a similar issue and if there is a known reason for this behavior. Additionally, I'm curious if a bundled native app, later published in the Android app store, might also run under the Chrome engine and potentially exhibit the same problem.

Any insights or suggestions would be greatly appreciated.

Best regards,
MK

**Comment by TiagoCavalcante** [comment]
@MainzerKaiser can you check if this was fixed in the new version (1.0.10)?
