### ISSUE TITLE
Setting initial rotation without locking angles

### ISSUE THREAD

**Issue by ninjz** [TiagoCavalcante/r3f-native-orbitcontrols#32]
I would like to set the initial horizontal rotation of the camera orbit. I am locking the vertical rotation so I was able to do that by setting min and max Polar angles. However, if I want to set the initial rotation on the y axis then I don't see anything that can do that without locking the Azimuth angle.

```jsx
          <OrbitControls
            target={cameraTarget}
            enableZoom={false}
            enablePan={false}
            enableRotate
            maxPolarAngle={cameraRotation.v}
            minPolarAngle={cameraRotation.v}
            rotateSpeed={1}
            dampingFactor={0.1}
          />
```

Is there a way to achieve this behavior?

**Comment by TiagoCavalcante** [comment]
@ninjz sorry for the long delay in answering your question, I didn't have much time to work on this project in the last few days.

If I understand your question correctly, you can do this by modifying the target of the camera (with the `target` property) and using [Vector3.setFromSpherical](https://threejs.org/docs/#api/en/math/Vector3.setFromSpherical) to obtain the desired rotation.

Can you look at this?

If that doesn't solve the problem, I can implement this directly in this lib.

**Comment by TiagoCavalcante** [comment]
@ninjz I'm closing this now, please re-open it if the problem wasn't solved.
