### ISSUE TITLE
Camera position is slightly off at the start

### ISSUE THREAD

**Issue by lexengineer** [TiagoCavalcante/r3f-native-orbitcontrols#41]
Hello everyone 👋 

Looks like I have an issue with camera position when I add orbit controls to my scene. For some reason camera is slightly different comparing to if I have my scene without orbit controls at all. So I wonder if orbit controls somehow modify the camera on start? To make it clear, I do not touch the screen. I just open my scene and it is there right away. Any advice is appreciated. Thank you.

**Comment by TiagoCavalcante** [comment]
Hi @lexengineer, thanks for creating the issue!

Can you check if the error is still happening after the latest release (1.0.12)?

**Comment by lexengineer** [comment]
> Hi @lexengineer, thanks for creating the issue!
> 
> Can you check if the error is still happening after the latest release (1.0.12)?

Unfortunately it did not solve the issue. This could be something on my side potentially. I will try to reproduce it with a clean app. But any advice is welcome of course. Thank you.

**Comment by TiagoCavalcante** [comment]
@lexengineer I looked at it, and yes, the orbit controls may modify the camera. Although it isn't its position, it is its target. You must pass `target` as a parameter to the orbit controls to have the same target.

[https://github.com/TiagoCavalcante/r3f-native-orbitcontrols/blob/0cfb50c069967620dd89f4f5a20ee2f853e2fc4e/src/index.tsx#L22]:comment

**Comment by lexengineer** [comment]
@TiagoCavalcante Thank you for that. I will give it a try. Closing this for now.
